# Generated by Django 5.1.5 on 2025-02-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sucursal', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('reporte', models.CharField(max_length=50)),
                ('falla', models.CharField(max_length=50)),
                ('coordinador', models.CharField(max_length=50)),
                ('estatus', models.BooleanField(default=False)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('personal', models.CharField(blank=True, max_length=50, null=True)),
                ('encargado', models.CharField(blank=True, max_length=50, null=True)),
                ('refrigerante', models.CharField(blank=True, max_length=50, null=True)),
                ('kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ods_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
