# Generated by Django 5.1.5 on 2025-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='reporte',
            field=models.CharField(max_length=50),
        ),
    ]
