# Generated by Django 5.1.5 on 2025-02-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reporte_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='urgencia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
