# Generated by Django 5.1.5 on 2025-02-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reporte_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='estatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
