# Generated by Django 5.1.5 on 2025-03-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reporte_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='reporte',
            field=models.CharField(max_length=75),
        ),
    ]
