# Generated by Django 5.1.5 on 2025-02-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reporte_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
