# Generated by Django 5.1.5 on 2025-02-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reporte_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='estatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
