# Generated by Django 5.1.5 on 2025-02-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reporte_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='ejecutor',
            new_name='personal',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
