# Generated by Django 5.1.5 on 2025-03-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_detallesolicitud_completado_alter_reporte_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='completado',
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
