# Generated by Django 5.1.5 on 2025-03-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_detallesolicitud_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='sucursal',
            field=models.CharField(default='Plaza Venezuela', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
