# Generated by Django 5.1.5 on 2025-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_solicitudmaterial_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudmaterial',
            name='materiales',
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
