# Generated by Django 5.1.5 on 2025-04-25 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_solicitudmaterial_materiales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
