# Generated by Django 5.1.5 on 2025-04-25 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_solicitudmaterial_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
