# Generated by Django 5.1.5 on 2025-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_solicitudmaterial_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudmaterial',
            name='aprobada',
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
    ]
