# Generated by Django 5.1.5 on 2025-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_solicitudmaterial_aprobada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='analista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
