# Generated by Django 5.1.5 on 2025-08-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
